# Generated by Django 3.2.23 on 2024-02-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0004_cantact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantact',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
